### ISSUE TITLE
Linux|Wayland webview does not attach to parent

### ISSUE THREAD

**Issue by pythoneer** [fltk-rs/webview#3]
On Wayland the webview is opening as a separate window 

![Screenshot from 2021-07-11 11-11-19](https://user-images.githubusercontent.com/1102097/125189612-2cf1f600-e239-11eb-8d6b-02092fbbe066.png)

**Comment by MoAlyousef** [comment]
It appears the XEmbed protocol doesn't work on wayland/xwayland unfortunately. The FLTK coredevs are currently working on a native wayland backend, hopefully this would work.

**Comment by MoAlyousef** [comment]
A temporary workaround on wayland is running an app with GDK_BACKEND=x11

```
GDK_BACKEND=x11 ./myapp
```
This should force webkitgtk to give an x11 xid which can be embedded in another app. 

Embedding in wayland doesn’t seem to be supported currently, even for gtk apps:
https://discourse.gnome.org/t/embedding-external-window-in-gtk-window/2371/9

**Comment by pythoneer** [comment]
I think this is the right way of doing it anyway – for whatever reason i didn't thought about that in the first place but this is how many application are doing it. I think we can close the issue and wait for a "better" solution from the fltk core devs. Maybe a note in the readme could help directing people to use `GDK_BACKEND=x11`

**Comment by MoAlyousef** [comment]
Thank you. ill add that along with install instructions for webkitgtk.
